version: "2"
services:
  resolver:
    image: node:17
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 8081:3000
    command: "npm start"