version: "2"
services:
  resolver:
    container_name: r.metaweave.xyz
    image: metaweave-resolver
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /home/node/app
    ports:
      - 3110:3000